// <auto-generated />
using System;
using ISOCI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241222193704_auth")]
    partial class auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminParamsEntityHistoryEntity", b =>
                {
                    b.Property<long>("ApminParamsId")
                        .HasColumnType("bigint");

                    b.Property<long>("HistoriesId")
                        .HasColumnType("bigint");

                    b.HasKey("ApminParamsId", "HistoriesId");

                    b.HasIndex("HistoriesId");

                    b.ToTable("AdminParamsEntityHistoryEntity");
                });

            modelBuilder.Entity("HistoryEntityUserParamsEntity", b =>
                {
                    b.Property<long>("HistoriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserParamsId")
                        .HasColumnType("bigint");

                    b.HasKey("HistoriesId", "UserParamsId");

                    b.HasIndex("UserParamsId");

                    b.ToTable("HistoryEntityUserParamsEntity");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.AdminParamsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ExpressionEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ParamValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ExpressionEntityId");

                    b.ToTable("AdminParams");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.ExpressionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExpressionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Expressions");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.HistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpressionId")
                        .HasColumnType("bigint");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ExpressionId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.UserParamsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ParamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ParamValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("UserParams");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdminParamsEntityHistoryEntity", b =>
                {
                    b.HasOne("ISOCI.DAL.Entities.AdminParamsEntity", null)
                        .WithMany()
                        .HasForeignKey("ApminParamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISOCI.DAL.Entities.HistoryEntity", null)
                        .WithMany()
                        .HasForeignKey("HistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistoryEntityUserParamsEntity", b =>
                {
                    b.HasOne("ISOCI.DAL.Entities.HistoryEntity", null)
                        .WithMany()
                        .HasForeignKey("HistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISOCI.DAL.Entities.UserParamsEntity", null)
                        .WithMany()
                        .HasForeignKey("UserParamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.AdminParamsEntity", b =>
                {
                    b.HasOne("ISOCI.DAL.Entities.ExpressionEntity", null)
                        .WithMany("AdminParams")
                        .HasForeignKey("ExpressionEntityId");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.HistoryEntity", b =>
                {
                    b.HasOne("ISOCI.DAL.Entities.ExpressionEntity", "Expression")
                        .WithMany()
                        .HasForeignKey("ExpressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expression");
                });

            modelBuilder.Entity("ISOCI.DAL.Entities.ExpressionEntity", b =>
                {
                    b.Navigation("AdminParams");
                });
#pragma warning restore 612, 618
        }
    }
}
